version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
